//! Rust guest interface for Dekopon provider components.
//!
//! Provider authors implement [`Provider`] using ordinary domain types and export it through
//! [`export_provider_with_cli!`], which supplies the JSON-over-WIT adapter component hosts call.
//! A model reaches a provider only through the command words it declares: `gh --help` renders a
//! page, and `gh pr view 7` proposes a capability the broker then authorizes. A host refuses to
//! start with a provider that declares capabilities and no command word, since nothing could reach
//! them.
//!
//! Hand-rolled argv handling — matching on slices and shifting values out by hand — is the
//! baseline contract every command-line provider can rely on. The optional `clap` feature adds
//! [`cli`], the encouraged layer over it: [`cli::run_command`] renders help, a version, and usage
//! errors from a declared `clap::Command` tree and hands parsed matches to a dispatch closure, and
//! the crate re-exports [`clap`] so a guest builds its tree against the SDK's exact clap without
//! declaring the dependency itself.
//!
//! The optional `host` feature adds [`host`], the Wasmtime plumbing both Dekopon hosts share. It is
//! off by default and no guest build enables it.

#![forbid(unsafe_code)]

use std::fmt;

pub use dekopon_capability::EffectKind;
pub use dekopon_core::{CapabilityId, ProviderId, RiskLevel, SecretDrn, SecretUseProposal};
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[cfg(feature = "clap")]
pub use clap;

#[cfg(feature = "clap")]
pub mod cli;
#[cfg(feature = "host")]
pub mod host;

/// The component WIT contract generated by this SDK.
pub const PROVIDER_WIT: &str = include_str!("../wit/provider.wit");

/// Version of the component manifest returned by a provider.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ProviderApiVersion {
    /// Initial experimental provider contract.
    #[serde(rename = "dekopon.dev/provider/v1alpha1")]
    V1Alpha1,
}

/// Manifest returned by a provider component.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ProviderManifest {
    /// Provider manifest API version.
    pub api_version: ProviderApiVersion,
    /// Stable provider identity.
    pub id: ProviderId,
    /// Concise operator-facing description.
    pub description: String,
    /// Capabilities implemented by this component.
    pub capabilities: Vec<ProviderCapability>,
    /// Command words this provider contributes to the sandboxed shell.
    ///
    /// Each is a bare word a model may type, run through [`Provider::run_command`], and together
    /// they are the only way a model reaches this provider's capabilities. A manifest that declares
    /// capabilities and no word, or a word without the component exporting `run-command`, is
    /// refused at load, and a word colliding with a shell builtin, a refused word, a control word,
    /// or another provider's is a startup failure naming every conflict at once.
    ///
    /// Defaulted so a manifest omitting the field still decodes and is refused by name in that
    /// startup report, rather than as an undecodable manifest.
    #[serde(default)]
    pub command_words: Vec<String>,
}

/// One prompt-visible capability exported by a provider component.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ProviderCapability {
    /// Stable capability identity.
    pub id: CapabilityId,
    /// Concise model- and operator-facing description.
    pub description: String,
    /// Effect classification. Immediate mode accepts only [`EffectKind::ReadOnly`].
    pub effect: EffectKind,
    /// Coarse risk classification available to callers.
    pub risk: RiskLevel,
    /// Object-shaped JSON Schema supplied to a model as function parameters.
    pub input_schema: Value,
}

/// Rust implementation contract for a provider component.
pub trait Provider {
    /// Describes the provider and its prompt-visible capabilities.
    fn manifest() -> ProviderManifest;

    /// Executes one capability against syntactically decoded, otherwise untrusted JSON input.
    ///
    /// The immediate host supplies no ambient I/O. A provider-owned world may declare imports
    /// such as buffered HTTP; the broker host supplies and links them, then gates calls through
    /// authorization.
    fn invoke(capability: &CapabilityId, input: Value) -> Result<Value, ProviderError>;

    /// Runs one command word's argv the way the upstream command-line tool would.
    ///
    /// This is how a model reaches the provider: `gh pr view 7 -R owner/repo` becoming
    /// `gh.pull-request.read` with a typed input. The command word is selected before this call;
    /// `argv` contains only the arguments after it.
    ///
    /// A [`CommandRun::Proposal`] is **pure and grants nothing**: it is authorized on the path every
    /// capability takes — constraint-set lookup, Cedar evaluation, credential injection at the
    /// native HTTP boundary — so naming a capability the caller was not granted produces a denial,
    /// not an escalation. A proposal may also name one secret use
    /// ([`CommandInvocation::secret_use`]), which the broker authorizes like any other; the secret
    /// it names never reaches the provider. `--help`, `--version`, and usage errors come back as
    /// [`CommandRun::Rendered`] text with an exit status, printed by the shell and authorizing
    /// nothing. A decline is `Err(ProviderError)`, reported to the model as a usage error.
    ///
    /// `stdin` is the value piped into the word, `None` when nothing was piped. The run happens
    /// before authorization, so it must not depend on host imports; a host may refuse a component
    /// that touches one here.
    fn run_command(argv: &[String], stdin: Option<&str>) -> Result<CommandRun, ProviderError>;
}

/// One capability proposal produced by [`Provider::run_command`].
#[derive(Clone, Debug, PartialEq)]
pub struct CommandInvocation {
    /// The capability the command word maps to.
    pub capability: CapabilityId,
    /// The input object assembled from the arguments.
    pub input: Value,
    /// The one secret use the proposal asks the broker to authorize beside the capability.
    ///
    /// A public DRN and the native sink to render it in, such as an HTTP `Authorization` header.
    /// It is untrusted intent rather than authority: the broker authorizes it separately and
    /// matches an owner-authored use binding, and the provider never receives the secret.
    pub secret_use: Option<SecretUseProposal>,
}

/// What one command-word run produced, from [`Provider::run_command`].
///
/// Only the proposal reaches authorization. Rendered text is shown to the model exactly as a
/// command-line program's output would be — help on stdout at status 0, a usage error on stderr
/// at status 2 — and grants nothing.
#[derive(Clone, Debug, PartialEq)]
pub enum CommandRun {
    /// The argv maps to one capability proposal, authorized as any other.
    Proposal(CommandInvocation),
    /// The argv was answered by the guest alone, as a command-line program prints and exits.
    Rendered {
        /// Text for the shell's standard output; capturable by `$( )`.
        stdout: String,
        /// Text for the shell's standard error; visible to the model, never captured.
        stderr: String,
        /// Exit status the shell reports for the word.
        status: u8,
    },
}

impl CommandRun {
    /// A capability proposal for `capability` with `input` assembled from the arguments, naming
    /// no secret use.
    #[must_use]
    pub fn proposal(capability: CapabilityId, input: Value) -> Self {
        Self::Proposal(CommandInvocation {
            capability,
            input,
            secret_use: None,
        })
    }

    /// Text on standard output with an exit status and nothing on standard error: a help page,
    /// a version line.
    #[must_use]
    pub fn rendered(stdout: impl Into<String>, status: u8) -> Self {
        Self::Rendered {
            stdout: stdout.into(),
            stderr: String::new(),
            status,
        }
    }

    /// Text on standard error with an exit status and nothing on standard output: a usage error,
    /// an unknown subcommand.
    #[must_use]
    pub fn rendered_error(stderr: impl Into<String>, status: u8) -> Self {
        Self::Rendered {
            stdout: String::new(),
            stderr: stderr.into(),
            status,
        }
    }
}

/// Provider-declared invocation failure.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProviderError {
    code: String,
    message: String,
}

impl ProviderError {
    /// Creates a provider error with a stable machine code and bounded human message.
    #[must_use]
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
        }
    }

    /// Returns the machine-readable code.
    #[must_use]
    pub fn code(&self) -> &str {
        &self.code
    }

    /// Returns the human-readable message.
    #[must_use]
    pub fn message(&self) -> &str {
        &self.message
    }
}

impl fmt::Display for ProviderError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}: {}", self.code, self.message)
    }
}

impl std::error::Error for ProviderError {}

/// JSON response returned across the WIT boundary.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(tag = "outcome", rename_all = "camelCase", deny_unknown_fields)]
pub enum ComponentResponse {
    /// Provider execution completed and returned JSON output.
    Succeeded {
        /// Capability-specific result.
        output: Value,
    },
    /// Provider rejected or failed the operation without trapping.
    Failed {
        /// Stable failure detail.
        error: ComponentFailure,
    },
}

/// Serializable provider failure carried by [`ComponentResponse::Failed`].
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ComponentFailure {
    /// Stable provider-specific code.
    pub code: String,
    /// Bounded human-readable detail.
    pub message: String,
}

/// JSON result of a command-word run, returned across the `run-command` WIT boundary.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(tag = "outcome", rename_all = "camelCase", deny_unknown_fields)]
pub enum CommandRunOutcome {
    /// The argv maps to one capability proposal.
    Proposed {
        /// Capability the command word named.
        capability: CapabilityId,
        /// Input object assembled from the arguments.
        input: Value,
        /// Secret use the proposal names, under the wire key `secretUse`; absent when it names
        /// none, so a proposal without one keeps its earlier shape.
        #[serde(rename = "secretUse", default, skip_serializing_if = "Option::is_none")]
        secret_use: Option<SecretUseProposal>,
    },
    /// The guest answered by itself, as a command-line program prints and exits.
    Rendered {
        /// Text for the shell's standard output.
        stdout: String,
        /// Text for the shell's standard error.
        stderr: String,
        /// Exit status the shell reports for the word.
        status: u8,
    },
    /// The provider declined this argv.
    Failed {
        /// Stable failure detail, reported to the model as a usage error.
        error: ComponentFailure,
    },
}

/// Last-resort [`ComponentResponse`] when the real one cannot be serialized.
///
/// Hand-written because the failing operation is the encoder itself.
/// `fallback_literals_decode_into_their_wire_types` pins it to the type.
const INVOKE_SERIALIZATION_FALLBACK: &str = r#"{"outcome":"failed","error":{"code":"serialization-failed","message":"provider response could not be serialized"}}"#;

/// Last-resort [`CommandRunOutcome`] when the real one cannot be serialized.
///
/// Hand-written for the same reason as [`INVOKE_SERIALIZATION_FALLBACK`], and pinned by the same
/// test.
const RUN_SERIALIZATION_FALLBACK: &str = r#"{"outcome":"failed","error":{"code":"serialization-failed","message":"command run could not be serialized"}}"#;

/// Manifest returned when `P::manifest()` cannot be serialized.
///
/// A host refuses this manifest either way — it declares no capabilities — but the description
/// carries the serialization error rather than being empty, so the refusal is traceable to the
/// real cause instead of sending an operator hunting for a blank description that exists nowhere
/// in their source.
fn describe_fallback(error: &serde_json::Error) -> String {
    serde_json::json!({
        "apiVersion": "dekopon.dev/provider/v1alpha1",
        "id": "invalid",
        "description": format!("manifest serialization failed: {error}"),
        "capabilities": [],
    })
    .to_string()
}

#[doc(hidden)]
pub fn __describe<P: Provider>() -> String {
    serde_json::to_string(&P::manifest()).unwrap_or_else(|error| describe_fallback(&error))
}

#[doc(hidden)]
pub fn __invoke<P: Provider>(capability: String, input_json: String) -> String {
    let response = match capability.parse::<CapabilityId>() {
        Ok(capability) => match serde_json::from_str::<Value>(&input_json) {
            Ok(input) => match P::invoke(&capability, input) {
                Ok(output) => ComponentResponse::Succeeded { output },
                Err(error) => ComponentResponse::Failed {
                    error: ComponentFailure {
                        code: error.code,
                        message: error.message,
                    },
                },
            },
            Err(error) => ComponentResponse::Failed {
                error: ComponentFailure {
                    code: "invalid-input".to_owned(),
                    message: error.to_string(),
                },
            },
        },
        Err(error) => ComponentResponse::Failed {
            error: ComponentFailure {
                code: "invalid-capability".to_owned(),
                message: error.to_string(),
            },
        },
    };

    serde_json::to_string(&response)
        .unwrap_or_else(|_error| INVOKE_SERIALIZATION_FALLBACK.to_owned())
}

#[doc(hidden)]
pub fn __run_command<P: Provider>(argv: Vec<String>, stdin: Option<String>) -> String {
    let outcome = match P::run_command(&argv, stdin.as_deref()) {
        Ok(CommandRun::Proposal(invocation)) => CommandRunOutcome::Proposed {
            capability: invocation.capability,
            input: invocation.input,
            secret_use: invocation.secret_use,
        },
        Ok(CommandRun::Rendered {
            stdout,
            stderr,
            status,
        }) => CommandRunOutcome::Rendered {
            stdout,
            stderr,
            status,
        },
        Err(error) => CommandRunOutcome::Failed {
            error: ComponentFailure {
                code: error.code,
                message: error.message,
            },
        },
    };

    serde_json::to_string(&outcome).unwrap_or_else(|_error| RUN_SERIALIZATION_FALLBACK.to_owned())
}

/// Exports a [`Provider`] through caller-generated bindings: `describe`, `invoke`, and the
/// `run-command` export its command words run through.
///
/// The bindings module must be an identifier naming a world that includes
/// `dekopon:provider/provider-cli@0.3.0`. The world may add explicitly versioned imports such as
/// `dekopon:http/client@1.0.0`; imports remain structural requirements, only a broker host can
/// grant and implement them, and only `invoke` may reach one.
#[macro_export]
macro_rules! export_provider_with_cli {
    ($provider:ty, $bindings:ident) => {
        struct __DekoponProviderComponent;

        impl $bindings::Guest for __DekoponProviderComponent {
            fn describe() -> ::std::string::String {
                $crate::__describe::<$provider>()
            }

            fn invoke(
                capability: ::std::string::String,
                input_json: ::std::string::String,
            ) -> ::std::string::String {
                $crate::__invoke::<$provider>(capability, input_json)
            }

            fn run_command(
                argv: ::std::vec::Vec<::std::string::String>,
                stdin: ::std::option::Option<::std::string::String>,
            ) -> ::std::string::String {
                $crate::__run_command::<$provider>(argv, stdin)
            }
        }

        $bindings::export!(
            __DekoponProviderComponent with_types_in $bindings
        );
    };
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{
        __describe, __invoke, __run_command, CapabilityId, CommandInvocation, CommandRun,
        CommandRunOutcome, ComponentFailure, ComponentResponse, EffectKind,
        INVOKE_SERIALIZATION_FALLBACK, Provider, ProviderApiVersion, ProviderCapability,
        ProviderError, ProviderManifest, RUN_SERIALIZATION_FALLBACK, RiskLevel, SecretUseProposal,
        describe_fallback,
    };

    const UPPER: &str = "cli-probe.upper";
    const DRN: &str = "drn:com.example:secret:prod:api/token";
    const HELP: &str = "Usage: probe upper [-]\n       probe upper --bearer <DRN>\n";

    fn upper() -> CapabilityId {
        UPPER.parse().expect("valid capability fixture")
    }

    /// A hand-rolled command-line provider: shifts values out of argv, no argument parser.
    struct Probe;

    impl Provider for Probe {
        fn manifest() -> ProviderManifest {
            ProviderManifest {
                api_version: ProviderApiVersion::V1Alpha1,
                id: "cli-probe".parse().expect("valid provider fixture"),
                description: "Upper-cases text".to_owned(),
                command_words: vec!["probe".to_owned()],
                capabilities: vec![ProviderCapability {
                    id: upper(),
                    description: "Upper-cases text".to_owned(),
                    effect: EffectKind::ReadOnly,
                    risk: RiskLevel::Low,
                    input_schema: json!({"type": "object"}),
                }],
            }
        }

        fn invoke(
            capability: &CapabilityId,
            input: serde_json::Value,
        ) -> Result<serde_json::Value, ProviderError> {
            match (
                capability.as_str(),
                input.get("text").and_then(serde_json::Value::as_str),
            ) {
                (UPPER, Some(text)) => Ok(json!({"text": text.to_uppercase()})),
                _ => Err(ProviderError::new("unsupported", capability.to_string())),
            }
        }

        fn run_command(argv: &[String], stdin: Option<&str>) -> Result<CommandRun, ProviderError> {
            match argv {
                [flag] if flag == "--help" => Ok(CommandRun::rendered(HELP, 0)),
                [word, dash] if word == "upper" && dash == "-" => match stdin {
                    Some(text) => Ok(CommandRun::proposal(upper(), json!({"text": text}))),
                    None => Ok(CommandRun::rendered_error(
                        "probe: `-` needs piped input\n",
                        2,
                    )),
                },
                [word] if word == "upper" => Ok(CommandRun::proposal(upper(), json!({}))),
                [word, flag, drn] if word == "upper" && flag == "--bearer" => {
                    let secret = drn.parse().map_err(|error| {
                        ProviderError::new("usage", format!("--bearer: {error}"))
                    })?;
                    Ok(CommandRun::Proposal(CommandInvocation {
                        capability: upper(),
                        input: json!({}),
                        secret_use: Some(SecretUseProposal::HttpBearer { secret }),
                    }))
                }
                _ => Err(ProviderError::new("usage", "probe upper [-]")),
            }
        }
    }

    fn run<P: Provider>(argv: &[&str], stdin: Option<&str>) -> CommandRunOutcome {
        let argv = argv.iter().map(|word| (*word).to_owned()).collect();
        serde_json::from_str(&__run_command::<P>(argv, stdin.map(str::to_owned)))
            .expect("command run parses")
    }

    #[test]
    fn adapter_serializes_the_typed_manifest() {
        let manifest: ProviderManifest =
            serde_json::from_str(&__describe::<Probe>()).expect("manifest parses");
        assert_eq!(manifest.id.as_str(), "cli-probe");
        assert_eq!(manifest.command_words, ["probe"]);
    }

    /// No unknown field is accepted, the retired `idempotency` included. The refusal names it.
    #[test]
    fn a_manifest_carrying_any_other_unknown_field_is_still_refused() {
        for unknown in ["idempotency", "retries", "idempotencyKey"] {
            let error = serde_json::from_value::<ProviderCapability>(json!({
                "id": UPPER,
                "description": "Upper-cases text",
                "effect": "read-only",
                "risk": "Low",
                unknown: "whatever",
                "inputSchema": {"type": "object"},
            }))
            .expect_err("an unknown manifest field must be refused");

            assert!(
                error.to_string().contains(unknown),
                "the refusal must name {unknown}, got {error}"
            );
        }
    }

    #[test]
    fn adapter_invokes_rust_provider_implementations() {
        let response: ComponentResponse = serde_json::from_str(&__invoke::<Probe>(
            UPPER.to_owned(),
            r#"{"text":"hello"}"#.to_owned(),
        ))
        .expect("response parses");

        assert_eq!(
            response,
            ComponentResponse::Succeeded {
                output: json!({"text": "HELLO"})
            }
        );
    }

    #[test]
    fn adapter_turns_invalid_identifiers_into_failures() {
        let response: ComponentResponse =
            serde_json::from_str(&__invoke::<Probe>("Not Valid".to_owned(), "{}".to_owned()))
                .expect("response parses");

        let ComponentResponse::Failed { error } = response else {
            panic!("an invalid identifier must fail, got {response:?}");
        };
        assert_eq!(error.code, "invalid-capability");
        assert!(
            error
                .message
                .contains("must start with a lowercase ASCII letter or digit"),
            "{error:?}"
        );
    }

    #[test]
    fn the_run_adapter_encodes_each_outcome_a_hand_rolled_provider_returns() {
        assert_eq!(
            run::<Probe>(&["--help"], None),
            CommandRunOutcome::Rendered {
                stdout: HELP.to_owned(),
                stderr: String::new(),
                status: 0,
            }
        );
        assert_eq!(
            run::<Probe>(&["upper", "-"], None),
            CommandRunOutcome::Rendered {
                stdout: String::new(),
                stderr: "probe: `-` needs piped input\n".to_owned(),
                status: 2,
            }
        );
        assert_eq!(
            run::<Probe>(&["upper", "-"], Some("hello")),
            CommandRunOutcome::Proposed {
                capability: upper(),
                input: json!({"text": "hello"}),
                secret_use: None,
            }
        );
        assert_eq!(
            run::<Probe>(&["bogus"], None),
            CommandRunOutcome::Failed {
                error: ComponentFailure {
                    code: "usage".to_owned(),
                    message: "probe upper [-]".to_owned(),
                },
            }
        );
    }

    /// The secret use a provider proposes reaches the host unchanged, and a DRN the provider
    /// refuses to parse is declined naming why.
    #[test]
    fn the_run_adapter_carries_a_proposed_secret_use_through() {
        assert_eq!(
            run::<Probe>(&["upper", "--bearer", DRN], None),
            CommandRunOutcome::Proposed {
                capability: upper(),
                input: json!({}),
                secret_use: Some(SecretUseProposal::HttpBearer {
                    secret: DRN.parse().expect("canonical DRN fixture"),
                }),
            }
        );
        let encoded = __run_command::<Probe>(
            vec!["upper".to_owned(), "--bearer".to_owned(), DRN.to_owned()],
            None,
        );
        assert!(
            encoded.contains(&format!(
                r#""secretUse":{{"kind":"httpBearer","secret":"{DRN}"}}"#
            )),
            "{encoded}"
        );

        let CommandRunOutcome::Failed { error } =
            run::<Probe>(&["upper", "--bearer", "vault://token"], None)
        else {
            panic!("a malformed DRN must be declined");
        };
        assert_eq!(error.code, "usage");
        assert!(
            error
                .message
                .starts_with("--bearer: secret DRN must be canonical"),
            "{error:?}"
        );
    }

    /// The wire tags are the host's contract; pin them so a rename shows up here, not in a host.
    #[test]
    fn run_outcomes_serialize_under_their_documented_tags() {
        let encoded = __run_command::<Probe>(vec!["--help".to_owned()], None);
        assert!(
            encoded.starts_with(r#"{"outcome":"rendered","#),
            "{encoded}"
        );
        let encoded = __run_command::<Probe>(vec!["upper".to_owned()], None);
        assert!(
            encoded.starts_with(r#"{"outcome":"proposed","#),
            "{encoded}"
        );
        let encoded = __run_command::<Probe>(vec!["bogus".to_owned()], None);
        assert!(encoded.starts_with(r#"{"outcome":"failed","#), "{encoded}");
    }

    /// A proposal naming a secret use carries it under `secretUse`; one naming none has exactly
    /// the shape it had before the field existed, in both directions.
    #[test]
    fn a_proposal_carries_its_secret_use_under_secret_use_and_omits_it_when_absent() {
        let with = CommandRunOutcome::Proposed {
            capability: upper(),
            input: json!({"text": "hello"}),
            secret_use: Some(SecretUseProposal::HttpBasic {
                secret: DRN.parse().expect("canonical DRN fixture"),
                username: "user-a".to_owned(),
            }),
        };
        let encoded = serde_json::to_string(&with).expect("a proposal serializes");
        assert_eq!(
            encoded,
            r#"{"outcome":"proposed","capability":"cli-probe.upper","input":{"text":"hello"},"secretUse":{"kind":"httpBasic","secret":"drn:com.example:secret:prod:api/token","username":"user-a"}}"#
        );
        assert_eq!(
            serde_json::from_str::<CommandRunOutcome>(&encoded).expect("the proposal decodes"),
            with
        );

        let without = CommandRunOutcome::Proposed {
            capability: upper(),
            input: json!({"text": "hello"}),
            secret_use: None,
        };
        let encoded = serde_json::to_string(&without).expect("a proposal serializes");
        assert_eq!(
            encoded,
            r#"{"outcome":"proposed","capability":"cli-probe.upper","input":{"text":"hello"}}"#
        );
        assert_eq!(
            serde_json::from_str::<CommandRunOutcome>(&encoded).expect("the proposal decodes"),
            without
        );
    }

    /// The decode side of the same contract: a host accepts this shape and nothing adjacent to it.
    #[test]
    fn a_run_outcome_decodes_only_its_own_wire_shape() {
        let outcome = serde_json::from_str::<CommandRunOutcome>(
            r#"{"outcome":"rendered","stdout":"Usage: fixture\n","stderr":"","status":0}"#,
        )
        .expect("a rendered page parses");
        assert_eq!(
            outcome,
            CommandRunOutcome::Rendered {
                stdout: "Usage: fixture\n".to_owned(),
                stderr: String::new(),
                status: 0,
            }
        );

        let error = serde_json::from_str::<CommandRunOutcome>(
            r#"{"outcome":"resolved","capability":"fixture.run","input":{}}"#,
        )
        .expect_err("the retired resolution tag is not a run outcome");
        assert!(error.to_string().contains("resolved"), "{error}");

        let error = serde_json::from_str::<CommandRunOutcome>(
            r#"{"outcome":"rendered","stdout":"","stderr":"","status":0,"extra":1}"#,
        )
        .expect_err("unknown fields are refused");
        assert!(error.to_string().contains("extra"), "{error}");

        let error = serde_json::from_str::<CommandRunOutcome>(&format!(
            r#"{{"outcome":"proposed","capability":"fixture.run","input":{{}},"secretUse":{{"kind":"httpBasic","secret":"{DRN}","username":"user:password"}}}}"#
        ))
        .expect_err("a Basic username carrying a colon is refused");
        assert!(error.to_string().contains("colon-free"), "{error}");
    }

    /// The manifest fallback must name why it exists.
    ///
    /// `id: "invalid"` parses as a `ProviderId`, so a host decodes this manifest and then refuses
    /// it. Before, the description was empty and the operator got "description must not be empty"
    /// for a description that appears nowhere in their source.
    #[test]
    fn describe_fallback_reports_the_serialization_error() {
        let error = serde_json::from_str::<ProviderManifest>("{").expect_err("malformed manifest");
        let encoded = describe_fallback(&error);

        let manifest =
            serde_json::from_str::<ProviderManifest>(&encoded).expect("fallback manifest decodes");
        assert_eq!(manifest.id.as_str(), "invalid");
        assert!(
            manifest
                .description
                .starts_with("manifest serialization failed: "),
            "{}",
            manifest.description
        );
        assert!(manifest.description.contains(&error.to_string()));
        assert!(manifest.capabilities.is_empty());
    }

    /// Each hardcoded fallback is written by hand because the encoder is what failed. Nothing but
    /// this test stops a new required field on one of these types from silently invalidating them.
    #[test]
    fn fallback_literals_decode_into_their_wire_types() {
        let error = serde_json::from_str::<ProviderManifest>("{").expect_err("malformed manifest");
        serde_json::from_str::<ProviderManifest>(&describe_fallback(&error))
            .expect("describe fallback decodes as a manifest");

        let response = serde_json::from_str::<ComponentResponse>(INVOKE_SERIALIZATION_FALLBACK)
            .expect("invoke fallback decodes as a component response");
        assert_eq!(
            response,
            ComponentResponse::Failed {
                error: ComponentFailure {
                    code: "serialization-failed".to_owned(),
                    message: "provider response could not be serialized".to_owned(),
                },
            }
        );

        let run = serde_json::from_str::<CommandRunOutcome>(RUN_SERIALIZATION_FALLBACK)
            .expect("run fallback decodes as a command run outcome");
        assert_eq!(
            run,
            CommandRunOutcome::Failed {
                error: ComponentFailure {
                    code: "serialization-failed".to_owned(),
                    message: "command run could not be serialized".to_owned(),
                },
            }
        );
    }
}
