//! Rust guest interface for Dekopon provider components.
//!
//! Provider authors implement [`Provider`] using ordinary domain types. [`export_provider!`]
//! supplies the JSON-over-WIT adapter required by `dekopon-provider-host`.

#![forbid(unsafe_code)]

use std::fmt;

pub use dekopon_capability::{EffectKind, Idempotency};
pub use dekopon_core::{CapabilityId, ProviderId, RiskLevel};
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// The component WIT contract generated by this SDK.
pub const PROVIDER_WIT: &str = include_str!("../wit/provider.wit");

/// Version of the component manifest returned by a provider.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ProviderApiVersion {
    /// Initial experimental provider contract.
    #[serde(rename = "dekopon.dev/provider/v1alpha1")]
    V1Alpha1,
}

/// Manifest returned by a provider component.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ProviderManifest {
    /// Provider manifest API version.
    pub api_version: ProviderApiVersion,
    /// Stable provider identity.
    pub id: ProviderId,
    /// Concise operator-facing description.
    pub description: String,
    /// Read-only capabilities implemented by this component.
    pub capabilities: Vec<ProviderCapability>,
    /// Command words this provider contributes to the sandboxed shell.
    ///
    /// Each is a bare word a model may type, resolved through [`Provider::resolve_command`]. A
    /// manifest that declares one without the component exporting `resolve-command` is refused at
    /// load, and a word colliding with a shell builtin, a refused word, a control word, or another
    /// provider's is a startup failure naming every conflict at once.
    ///
    /// Defaulted so a component built against `dekopon:provider@0.1.0` still loads, contributing
    /// none.
    #[serde(default)]
    pub command_words: Vec<String>,
}

/// One prompt-visible capability exported by a provider component.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ProviderCapability {
    /// Stable capability identity.
    pub id: CapabilityId,
    /// Concise model- and operator-facing description.
    pub description: String,
    /// Effect classification. Immediate mode accepts only [`EffectKind::ReadOnly`].
    pub effect: EffectKind,
    /// Coarse risk classification available to callers.
    pub risk: RiskLevel,
    /// Declared retry behavior.
    pub idempotency: Idempotency,
    /// Object-shaped JSON Schema supplied to a model as function parameters.
    pub input_schema: Value,
}

/// Rust implementation contract for a provider component.
pub trait Provider {
    /// Describes the provider and its prompt-visible capabilities.
    fn manifest() -> ProviderManifest;

    /// Executes one capability against syntactically decoded, otherwise untrusted JSON input.
    ///
    /// The immediate host supplies no ambient I/O. This function should be deterministic unless
    /// an eventual host interface explicitly provides a bounded source of nondeterminism.
    fn invoke(capability: &CapabilityId, input: Value) -> Result<Value, ProviderError>;

    /// Rewrites one argv into a capability proposal.
    ///
    /// This is where a provider implements the ergonomic spelling of its own capabilities —
    /// `gh pr view 7 -R owner/repo` becoming `gh.pull-request.read` with a typed input. The command
    /// word is selected before this call; `argv` contains only the arguments after it.
    ///
    /// It is a **pure rewrite and grants nothing**. What it returns is a proposal, authorized on
    /// exactly the path a direct `cap <id> {…}` call takes: constraint-set lookup, Cedar
    /// evaluation, credential injection at the native HTTP boundary. Naming a capability the
    /// caller was not granted produces a denial, not an escalation. It runs before authorization,
    /// so it must not depend on host imports; a host may refuse a component that touches one here.
    ///
    /// The default refuses, which is correct for the majority of providers: one that declares no
    /// command words can never be asked.
    fn resolve_command(argv: &[String]) -> Result<CommandInvocation, ProviderError> {
        let _ = argv;
        Err(ProviderError::new(
            "unsupported-command",
            "this provider declares no command words",
        ))
    }
}

/// One capability proposal produced by [`Provider::resolve_command`].
#[derive(Clone, Debug, PartialEq)]
pub struct CommandInvocation {
    /// The capability the command word maps to.
    pub capability: CapabilityId,
    /// The input object assembled from the arguments.
    pub input: Value,
}

/// Provider-declared invocation failure.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProviderError {
    code: String,
    message: String,
}

impl ProviderError {
    /// Creates a provider error with a stable machine code and bounded human message.
    #[must_use]
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
        }
    }

    /// Returns the machine-readable code.
    #[must_use]
    pub fn code(&self) -> &str {
        &self.code
    }

    /// Returns the human-readable message.
    #[must_use]
    pub fn message(&self) -> &str {
        &self.message
    }
}

impl fmt::Display for ProviderError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}: {}", self.code, self.message)
    }
}

impl std::error::Error for ProviderError {}

/// JSON response returned across the WIT boundary.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(tag = "outcome", rename_all = "camelCase", deny_unknown_fields)]
pub enum ComponentResponse {
    /// Provider execution completed and returned JSON output.
    Succeeded {
        /// Capability-specific result.
        output: Value,
    },
    /// Provider rejected or failed the operation without trapping.
    Failed {
        /// Stable failure detail.
        error: ComponentFailure,
    },
}

/// Serializable provider failure carried by [`ComponentResponse::Failed`].
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ComponentFailure {
    /// Stable provider-specific code.
    pub code: String,
    /// Bounded human-readable detail.
    pub message: String,
}

/// JSON result of a command-word rewrite, returned across the WIT boundary.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(tag = "outcome", rename_all = "camelCase", deny_unknown_fields)]
pub enum CommandResolution {
    /// The argv maps to one capability proposal.
    Resolved {
        /// Capability the command word named.
        capability: CapabilityId,
        /// Input object assembled from the arguments.
        input: Value,
    },
    /// The provider declined to rewrite this argv.
    Failed {
        /// Stable failure detail, reported to the model as a usage error.
        error: ComponentFailure,
    },
}

#[doc(hidden)]
pub mod __wit {
    wit_bindgen::generate!({
        path: "wit",
        world: "provider",
        pub_export_macro: true,
    });
}

/// Last-resort [`ComponentResponse`] when the real one cannot be serialized.
///
/// Hand-written because the failing operation is the encoder itself.
/// `fallback_literals_decode_into_their_wire_types` pins it to the type.
const INVOKE_SERIALIZATION_FALLBACK: &str = r#"{"outcome":"failed","error":{"code":"serialization-failed","message":"provider response could not be serialized"}}"#;

/// Last-resort [`CommandResolution`] when the real one cannot be serialized.
///
/// Hand-written for the same reason as [`INVOKE_SERIALIZATION_FALLBACK`], and pinned by the same
/// test.
const RESOLVE_SERIALIZATION_FALLBACK: &str = r#"{"outcome":"failed","error":{"code":"serialization-failed","message":"command resolution could not be serialized"}}"#;

/// Manifest returned when `P::manifest()` cannot be serialized.
///
/// A host refuses this manifest either way — it declares no capabilities — but the description
/// carries the serialization error rather than being empty, so the refusal is traceable to the
/// real cause instead of sending an operator hunting for a blank description that exists nowhere
/// in their source.
fn describe_fallback(error: &serde_json::Error) -> String {
    serde_json::json!({
        "apiVersion": "dekopon.dev/provider/v1alpha1",
        "id": "invalid",
        "description": format!("manifest serialization failed: {error}"),
        "capabilities": [],
    })
    .to_string()
}

#[doc(hidden)]
pub fn __describe<P: Provider>() -> String {
    serde_json::to_string(&P::manifest()).unwrap_or_else(|error| describe_fallback(&error))
}

#[doc(hidden)]
pub fn __invoke<P: Provider>(capability: String, input_json: String) -> String {
    let response = match capability.parse::<CapabilityId>() {
        Ok(capability) => match serde_json::from_str::<Value>(&input_json) {
            Ok(input) => match P::invoke(&capability, input) {
                Ok(output) => ComponentResponse::Succeeded { output },
                Err(error) => ComponentResponse::Failed {
                    error: ComponentFailure {
                        code: error.code,
                        message: error.message,
                    },
                },
            },
            Err(error) => ComponentResponse::Failed {
                error: ComponentFailure {
                    code: "invalid-input".to_owned(),
                    message: error.to_string(),
                },
            },
        },
        Err(error) => ComponentResponse::Failed {
            error: ComponentFailure {
                code: "invalid-capability".to_owned(),
                message: error.to_string(),
            },
        },
    };

    serde_json::to_string(&response)
        .unwrap_or_else(|_error| INVOKE_SERIALIZATION_FALLBACK.to_owned())
}

#[doc(hidden)]
pub fn __resolve_command<P: Provider>(argv: Vec<String>) -> String {
    let resolution = match P::resolve_command(&argv) {
        Ok(invocation) => CommandResolution::Resolved {
            capability: invocation.capability,
            input: invocation.input,
        },
        Err(error) => CommandResolution::Failed {
            error: ComponentFailure {
                code: error.code,
                message: error.message,
            },
        },
    };

    serde_json::to_string(&resolution)
        .unwrap_or_else(|_error| RESOLVE_SERIALIZATION_FALLBACK.to_owned())
}

/// Exports a Rust [`Provider`] implementation as the import-free Dekopon WIT world.
///
/// Provider crates with additional imports use [`export_provider_with_bindings!`] instead.
#[macro_export]
macro_rules! export_provider {
    ($provider:ty) => {
        struct __DekoponProviderComponent;

        impl $crate::__wit::Guest for __DekoponProviderComponent {
            fn describe() -> ::std::string::String {
                $crate::__describe::<$provider>()
            }

            fn invoke(
                capability: ::std::string::String,
                input_json: ::std::string::String,
            ) -> ::std::string::String {
                $crate::__invoke::<$provider>(capability, input_json)
            }
        }

        $crate::__wit::export!(
            __DekoponProviderComponent with_types_in $crate::__wit
        );
    };
}

/// Exports a Rust [`Provider`] implementation through caller-generated world bindings.
///
/// The bindings module must be an identifier that describes a world with the same root `describe`
/// and `invoke` exports. It may add explicitly versioned imports such as
/// `dekopon:http/client@1.0.0`. Imports remain structural requirements; only a broker host can
/// grant and implement them.
#[macro_export]
macro_rules! export_provider_with_bindings {
    ($provider:ty, $bindings:ident) => {
        struct __DekoponProviderComponent;

        impl $bindings::Guest for __DekoponProviderComponent {
            fn describe() -> ::std::string::String {
                $crate::__describe::<$provider>()
            }

            fn invoke(
                capability: ::std::string::String,
                input_json: ::std::string::String,
            ) -> ::std::string::String {
                $crate::__invoke::<$provider>(capability, input_json)
            }
        }

        $bindings::export!(
            __DekoponProviderComponent with_types_in $bindings
        );
    };
}

/// Exports a [`Provider`] that also contributes command words, through caller-generated bindings.
///
/// The bindings module must describe a world including `dekopon:provider/provider-commands`, so it
/// exports `resolve-command` alongside `describe` and `invoke`. Use this when the provider declares
/// `commandWords` in its manifest; [`export_provider_with_bindings!`] is the right macro otherwise.
#[macro_export]
macro_rules! export_provider_with_commands {
    ($provider:ty, $bindings:ident) => {
        struct __DekoponProviderComponent;

        impl $bindings::Guest for __DekoponProviderComponent {
            fn describe() -> ::std::string::String {
                $crate::__describe::<$provider>()
            }

            fn invoke(
                capability: ::std::string::String,
                input_json: ::std::string::String,
            ) -> ::std::string::String {
                $crate::__invoke::<$provider>(capability, input_json)
            }

            fn resolve_command(
                argv: ::std::vec::Vec<::std::string::String>,
            ) -> ::std::string::String {
                $crate::__resolve_command::<$provider>(argv)
            }
        }

        $bindings::export!(
            __DekoponProviderComponent with_types_in $bindings
        );
    };
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{
        __describe, __invoke, CapabilityId, CommandResolution, ComponentFailure, ComponentResponse,
        EffectKind, INVOKE_SERIALIZATION_FALLBACK, Idempotency, Provider, ProviderApiVersion,
        ProviderCapability, ProviderError, ProviderManifest, RESOLVE_SERIALIZATION_FALLBACK,
        RiskLevel, describe_fallback,
    };

    struct Echo;

    impl Provider for Echo {
        fn manifest() -> ProviderManifest {
            ProviderManifest {
                api_version: ProviderApiVersion::V1Alpha1,
                id: "echo".parse().expect("valid provider fixture"),
                description: "Echoes input".to_owned(),
                command_words: Vec::new(),
                capabilities: vec![ProviderCapability {
                    id: "echo.echo".parse().expect("valid capability fixture"),
                    description: "Echoes input".to_owned(),
                    effect: EffectKind::ReadOnly,
                    risk: RiskLevel::Low,
                    idempotency: Idempotency::Idempotent,
                    input_schema: json!({"type": "object"}),
                }],
            }
        }

        fn invoke(
            capability: &CapabilityId,
            input: serde_json::Value,
        ) -> Result<serde_json::Value, ProviderError> {
            if capability.as_str() == "echo.echo" {
                Ok(input)
            } else {
                Err(ProviderError::new("unsupported", capability.to_string()))
            }
        }
    }

    #[test]
    fn adapter_serializes_the_typed_manifest() {
        let manifest: ProviderManifest =
            serde_json::from_str(&__describe::<Echo>()).expect("manifest parses");
        assert_eq!(manifest.id.as_str(), "echo");
    }

    #[test]
    fn adapter_invokes_rust_provider_implementations() {
        let response: ComponentResponse = serde_json::from_str(&__invoke::<Echo>(
            "echo.echo".to_owned(),
            r#"{"message":"hello"}"#.to_owned(),
        ))
        .expect("response parses");

        assert_eq!(
            response,
            ComponentResponse::Succeeded {
                output: json!({"message": "hello"})
            }
        );
    }

    #[test]
    fn adapter_turns_invalid_identifiers_into_failures() {
        let response: ComponentResponse =
            serde_json::from_str(&__invoke::<Echo>("Not Valid".to_owned(), "{}".to_owned()))
                .expect("response parses");

        assert!(matches!(response, ComponentResponse::Failed { .. }));
    }

    /// The manifest fallback must name why it exists.
    ///
    /// `id: "invalid"` parses as a `ProviderId`, so a host decodes this manifest and then refuses
    /// it. Before, the description was empty and the operator got "description must not be empty"
    /// for a description that appears nowhere in their source.
    #[test]
    fn describe_fallback_reports_the_serialization_error() {
        let error = serde_json::from_str::<ProviderManifest>("{").expect_err("malformed manifest");
        let encoded = describe_fallback(&error);

        let manifest =
            serde_json::from_str::<ProviderManifest>(&encoded).expect("fallback manifest decodes");
        assert_eq!(manifest.id.as_str(), "invalid");
        assert!(
            manifest
                .description
                .starts_with("manifest serialization failed: "),
            "{}",
            manifest.description
        );
        assert!(manifest.description.contains(&error.to_string()));
        assert!(manifest.capabilities.is_empty());
    }

    /// Each hardcoded fallback is written by hand because the encoder is what failed. Nothing but
    /// this test stops a new required field on one of these types from silently invalidating them.
    #[test]
    fn fallback_literals_decode_into_their_wire_types() {
        let error = serde_json::from_str::<ProviderManifest>("{").expect_err("malformed manifest");
        serde_json::from_str::<ProviderManifest>(&describe_fallback(&error))
            .expect("describe fallback decodes as a manifest");

        let response = serde_json::from_str::<ComponentResponse>(INVOKE_SERIALIZATION_FALLBACK)
            .expect("invoke fallback decodes as a component response");
        assert_eq!(
            response,
            ComponentResponse::Failed {
                error: ComponentFailure {
                    code: "serialization-failed".to_owned(),
                    message: "provider response could not be serialized".to_owned(),
                },
            }
        );

        let resolution = serde_json::from_str::<CommandResolution>(RESOLVE_SERIALIZATION_FALLBACK)
            .expect("resolve fallback decodes as a command resolution");
        assert_eq!(
            resolution,
            CommandResolution::Failed {
                error: ComponentFailure {
                    code: "serialization-failed".to_owned(),
                    message: "command resolution could not be serialized".to_owned(),
                },
            }
        );
    }
}
