#!/usr/bin/env python3
"""Render the Homebrew formula for a published Dekopon release.

The formula is derived from the archives a release actually published, never
from a list hardcoded here. Which platforms Dekopon ships is a property of each
release; adding or dropping a target changes the next release's assets and this
script follows them. An unrecognized target is a hard error rather than a
silently dropped platform; a target this tap has deliberately retired is a
logged skip.

Inputs are the release's asset list and its downloaded `.sha256` sidecars, so
nothing is recomputed from the archives themselves.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

# Rust target triple -> the Homebrew `on_<os>` / `on_<arch>` block that selects it.
OFFERED = {
    "aarch64-apple-darwin": ("macos", "arm"),
    "aarch64-unknown-linux-gnu": ("linux", "arm"),
    "x86_64-unknown-linux-gnu": ("linux", "intel"),
}

# Targets a release may still carry that the tap deliberately does not offer.
#
# macOS Intel left the release matrix in dekopon-agents/dekopon#74, so 0.4.0
# onward publishes no `x86_64-apple-darwin` archive. Rendering 0.3.0's copy of
# it would be worse than declining to: `brew install` would succeed on an Intel
# Mac and then dead-end, because the next `brew upgrade` would find nothing for
# that platform. The tap serves the platforms the project supports, not every
# archive that exists in history.
#
# Recognized rather than deleted, because the unknown-target error below means
# "a target nobody wired up" and must keep meaning only that. Re-rendering a
# historical release is a normal skip, not a failure.
#
# Note the Linux half of x86-64 is untouched: `x86_64-unknown-linux-gnu` stays
# in OFFERED above.
RETIRED = {"x86_64-apple-darwin"}

OS_ORDER = ["macos", "linux"]
ARCH_ORDER = ["arm", "intel"]

DOWNLOAD = "https://github.com/{repository}/releases/download/{tag}/{name}"

TEMPLATE = '''# Dekopon publishes one archive per platform carrying all four executables, so
# one formula installs the whole system. Four formulae would each download the
# same tarball.
#
# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/{repository}, from the archives release {tag} published.
# Which platforms Dekopon supports is a property of each release, not of this
# tap. Edit the generator, not this file.
class Dekopon < Formula
  desc "Capability-oriented control plane for self-hosted AI agents"
  homepage "https://github.com/{repository}"
  license any_of: ["Apache-2.0", "MIT"]
  # No explicit `version`: Homebrew scans {version} out of the download URL, and
  # `brew audit --strict` rejects restating it.

{platforms}
  def install
    bin.install "dekopon", "dekopon-run", "dekopon-brokerd", "dekopond"
    pkgshare.install "providers"
    doc.install "README.md", "BROKER.md", "GATEWAY.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  def caveats
    <<~EOS
      Dekopon installed four executables:

        dekopon          local agent catalog and model-account CLI
        dekopon-run      one-shot runner: components, sandboxed shell, prompt loop
        dekopon-brokerd  the authorization broker daemon (Unix only)
        dekopond         the unprivileged chat gateway daemon (Unix only)

      dekopon and dekopon-run need no setup:

        dekopon --config ./dekopon.yaml validate
        dekopon-run inspect --provider ./some-provider.wasm

      dekopon-brokerd and dekopond are daemons. Nothing was started, and neither
      runs until you write it an owner-authored configuration file:

        dekopon-brokerd --config broker.yaml    #{{doc}}/BROKER.md
        dekopond --config gateway.yaml          #{{doc}}/GATEWAY.md

      The broker holds provider credentials and the only authorization path;
      read BROKER.md before enabling it.

      The example JSONPlaceholder provider component is at

        #{{pkgshare}}/providers/jsonplaceholder-provider.wasm

      It imports broker-owned HTTP, which makes it a broker provider: name that
      path in broker.yaml. `dekopon-run inspect` is deliberately import-free and
      refuses to instantiate it. The constraint set and Cedar policy it needs are
      in #{{pkgshare}}/providers/JSONPLACEHOLDER.md.

      The end-to-end walkthrough is examples/pr-summarizer-linter in the source tree:
      https://github.com/{repository}/tree/{tag}/examples/pr-summarizer-linter
    EOS
  end

  test do
    assert_match "dekopon #{{version}}", shell_output("#{{bin}}/dekopon --version")
    assert_match "dekopon-run #{{version}}", shell_output("#{{bin}}/dekopon-run --version")
    assert_match "dekopon-brokerd #{{version}}", shell_output("#{{bin}}/dekopon-brokerd --version")
    assert_match "dekopond #{{version}}", shell_output("#{{bin}}/dekopond --version")

    component = pkgshare/"providers/jsonplaceholder-provider.wasm"
    assert_path_exists component
    assert_equal "\\x00asm", component.binread(4), "example provider is not a Wasm component"

    # Exercise the catalog reader on a real cross-referenced catalog rather than
    # only proving the binaries start.
    (testpath/"dekopon.yaml").write <<~YAML
      apiVersion: dekopon.dev/v1alpha1
      kind: Provider
      metadata:
        name: jsonplaceholder
      spec:
        description: Example provider declaration
        type: http
        credentialRef: jsonplaceholder-default
      status: Unknown
      ---
      apiVersion: dekopon.dev/v1alpha1
      kind: Capability
      metadata:
        name: jsonplaceholder.posts.get
      spec:
        description: Read one JSONPlaceholder post
        provider: jsonplaceholder
        effect: read-only
        risk: Low
        idempotency: idempotent
        permissions:
          - operation: posts:read
      status: Unknown
      ---
      apiVersion: dekopon.dev/v1alpha1
      kind: Agent
      metadata:
        name: reader
      spec:
        description: Reads example posts and nothing else
        enabled: true
        capabilities:
          - jsonplaceholder.posts.get
        providers:
          - jsonplaceholder
        modelClass: analysis
        policyProfile: read-only
      status: Ready
    YAML

    assert_match "configuration valid",
                 shell_output("#{{bin}}/dekopon --config #{{testpath}}/dekopon.yaml validate")
    assert_equal "agent/reader",
                 shell_output("#{{bin}}/dekopon --config #{{testpath}}/dekopon.yaml get agents -o name").strip
  end
end
'''


def render_platforms(archives: dict[str, tuple[str, str]]) -> str:
    """archives maps target triple -> (url, sha256)."""
    by_os: dict[str, dict[str, tuple[str, str]]] = {}
    for target, payload in archives.items():
        operating_system, architecture = OFFERED[target]
        by_os.setdefault(operating_system, {})[architecture] = payload

    lines: list[str] = []
    for operating_system in OS_ORDER:
        architectures = by_os.get(operating_system)
        if not architectures:
            continue
        lines.append(f"  on_{operating_system} do")
        emitted = [
            architecture for architecture in ARCH_ORDER if architecture in architectures
        ]
        for index, architecture in enumerate(emitted):
            url, checksum = architectures[architecture]
            if index:
                lines.append("")
            lines.append(f"    on_{architecture} do")
            lines.append(f'      url "{url}"')
            lines.append(f'      sha256 "{checksum}"')
            lines.append("    end")
        lines.append("  end")
        lines.append("")
    return "\n".join(lines)


def read_checksums(
    directory: pathlib.Path, version: str
) -> dict[str, tuple[str, str]]:
    """Map target triple -> (archive name, sha256) from downloaded sidecars."""
    pattern = re.compile(
        rf"^dekopon-{re.escape(version)}-(?P<target>.+)\.tar\.gz\.sha256$"
    )
    found: dict[str, tuple[str, str]] = {}
    for sidecar in sorted(directory.iterdir()):
        match = pattern.match(sidecar.name)
        if not match:
            continue
        fields = sidecar.read_text(encoding="utf-8").split()
        if len(fields) != 2:
            raise SystemExit(f"{sidecar.name}: expected '<sha256>  <file>'")
        checksum, named = fields
        if not re.fullmatch(r"[0-9a-f]{64}", checksum):
            raise SystemExit(f"{sidecar.name}: {checksum!r} is not a sha256 digest")
        archive = sidecar.name.removesuffix(".sha256")
        if pathlib.PurePath(named).name != archive:
            raise SystemExit(f"{sidecar.name}: names {named}, expected {archive}")
        found[match.group("target")] = (archive, checksum)
    return found


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", default="dekopon-agents/dekopon")
    parser.add_argument("--tag", required=True, help="release tag, for example v0.3.0")
    parser.add_argument(
        "--checksums",
        required=True,
        type=pathlib.Path,
        help="directory holding the release's downloaded .sha256 sidecars",
    )
    parser.add_argument(
        "--assets",
        type=pathlib.Path,
        help="optional `gh release view --json assets` output to cross-check",
    )
    parser.add_argument("--output", required=True, type=pathlib.Path)
    arguments = parser.parse_args()

    if not re.fullmatch(r"v\d+\.\d+\.\d+(?:[-+].+)?", arguments.tag):
        raise SystemExit(f"{arguments.tag} is not a v<major>.<minor>.<patch> tag")
    version = arguments.tag[1:]

    checksums = read_checksums(arguments.checksums, version)
    if not checksums:
        raise SystemExit(
            f"no dekopon-{version}-<target>.tar.gz.sha256 sidecars in "
            f"{arguments.checksums}"
        )

    unknown = sorted(set(checksums) - set(OFFERED) - RETIRED)
    if unknown:
        raise SystemExit(
            "release publishes targets this generator cannot place in a Homebrew "
            f"block: {', '.join(unknown)}. Add them to OFFERED."
        )

    if arguments.assets:
        published = {
            asset["name"]
            for asset in json.loads(arguments.assets.read_text(encoding="utf-8"))[
                "assets"
            ]
        }
        archives = {
            name
            for name in published
            if name.startswith(f"dekopon-{version}-") and name.endswith(".tar.gz")
        }
        described = {archive for archive, _ in checksums.values()}
        if archives != described:
            raise SystemExit(
                "release archives and checksum sidecars disagree; "
                f"archives-without-sidecar={sorted(archives - described)}, "
                f"sidecar-without-archive={sorted(described - archives)}"
            )

    retired = sorted(set(checksums) & RETIRED)
    for target in retired:
        del checksums[target]
        print(
            f"skipping {target}: retired from the tap, see RETIRED in this script",
            file=sys.stderr,
        )
    if not checksums:
        raise SystemExit(
            f"{arguments.tag} publishes no target this tap offers; "
            f"retired={', '.join(retired) or 'none'}"
        )

    resolved = {
        target: (
            DOWNLOAD.format(
                repository=arguments.repository, tag=arguments.tag, name=archive
            ),
            checksum,
        )
        for target, (archive, checksum) in checksums.items()
    }

    formula = TEMPLATE.format(
        repository=arguments.repository,
        tag=arguments.tag,
        version=version,
        platforms=render_platforms(resolved),
    )
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(formula, encoding="utf-8")
    print(
        f"rendered {arguments.output} for {arguments.tag} from "
        f"{len(resolved)} archive(s): {', '.join(sorted(resolved))}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
