//! Bounded image generation through OpenAI's public Images API.
//!
//! This is a model client, not a provider capability. Its credential terminates inside the
//! unprivileged model boundary exactly like a chat-model credential, and generated bytes never
//! enter provider components, broker protocol, or model transcripts.

use std::{fmt, time::Duration};

use base64::{Engine as _, engine::general_purpose::STANDARD};
use dekopon_core::Redacted;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use ureq::Agent;

/// The one production endpoint used by [`OpenAiImageGenerator`].
const OPENAI_IMAGES_URL: &str = "https://api.openai.com/v1/images/generations";
/// Maximum model-authored generation prompt accepted by the client.
pub const MAX_IMAGE_PROMPT_BYTES: usize = 4 * 1024;
/// Maximum decoded generated image retained in memory or handed to a chat transport.
pub const MAX_GENERATED_IMAGE_BYTES: usize = 8 * 1024 * 1024;
/// JSON/base64 response ceiling. Base64 needs four bytes for each three decoded bytes; the fixed
/// allowance covers the small response envelope without turning it into an unbounded read.
const MAX_IMAGE_RESPONSE_BYTES: u64 =
    (MAX_GENERATED_IMAGE_BYTES as u64).div_ceil(3) * 4 + 64 * 1024;
const PNG_SIGNATURE: &[u8; 8] = b"\x89PNG\r\n\x1a\n";

/// One generated PNG, held only until the embedding chat transport accepts it.
///
/// `Debug` reports metadata and never bytes. Generated content is untrusted and can be several
/// megabytes; formatting it into a model transcript or telemetry record would be both a data leak
/// and an unbounded operational cost.
pub struct GeneratedImage {
    data: Vec<u8>,
}

impl GeneratedImage {
    /// Validates and owns one bounded PNG.
    pub fn from_png(data: Vec<u8>) -> Result<Self, ImageGenerationError> {
        if data.len() > MAX_GENERATED_IMAGE_BYTES {
            return Err(ImageGenerationError::TooLarge);
        }
        if !data.starts_with(PNG_SIGNATURE) {
            return Err(ImageGenerationError::InvalidImage);
        }
        Ok(Self { data })
    }

    /// IANA media type fixed by the generation request and validated from the bytes.
    #[must_use]
    pub const fn media_type(&self) -> &'static str {
        "image/png"
    }

    /// Gateway-owned filename; the model cannot choose a path or service-visible name.
    #[must_use]
    pub const fn filename(&self) -> &'static str {
        "generated-image.png"
    }

    /// Raw PNG bytes for the final transport upload.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.data
    }

    /// Consumes the image into its raw PNG bytes.
    #[must_use]
    pub fn into_bytes(self) -> Vec<u8> {
        self.data
    }
}

impl fmt::Debug for GeneratedImage {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GeneratedImage")
            .field("media_type", &self.media_type())
            .field("bytes", &self.data.len())
            .finish()
    }
}

/// Synchronous generation boundary used by the synchronous agent prompt loop.
pub trait ImageGenerator: Send + Sync {
    /// Actual configured client identity, never a prompt-selected target.
    fn model_identity(&self) -> (&str, &str) {
        ("adapter", "unreported")
    }
    /// Generates one bounded image from one model-authored prompt.
    fn generate(
        &self,
        prompt: &str,
        recorder: &dyn crate::usage::AttemptRecorder,
    ) -> Result<GeneratedImage, ImageGenerationError>;
}

/// OpenAI Images client fixed to the public production endpoint.
pub struct OpenAiImageGenerator {
    agent: Agent,
    endpoint: String,
    model: String,
    api_key: Redacted<String>,
}

impl OpenAiImageGenerator {
    /// Creates a bounded client for one explicitly configured GPT Image model.
    pub fn new(
        model: impl Into<String>,
        api_key: String,
        timeout: Duration,
    ) -> Result<Self, ImageGenerationError> {
        Self::with_endpoint(OPENAI_IMAGES_URL, model, api_key, timeout)
    }

    fn with_endpoint(
        endpoint: impl Into<String>,
        model: impl Into<String>,
        api_key: String,
        timeout: Duration,
    ) -> Result<Self, ImageGenerationError> {
        if timeout.is_zero() {
            return Err(ImageGenerationError::Configuration(
                "image generation timeout must be greater than zero".to_owned(),
            ));
        }
        let model = model.into();
        if model.trim().is_empty() {
            return Err(ImageGenerationError::Configuration(
                "image generation model must not be empty".to_owned(),
            ));
        }
        if api_key.trim().is_empty() {
            return Err(ImageGenerationError::Configuration(
                "image generation API key must not be empty".to_owned(),
            ));
        }
        let endpoint = endpoint.into();
        if endpoint.trim().is_empty() {
            return Err(ImageGenerationError::Configuration(
                "image generation endpoint must not be empty".to_owned(),
            ));
        }
        Ok(Self {
            agent: crate::agent(timeout),
            endpoint,
            model,
            api_key: Redacted::new(api_key),
        })
    }
}

impl ImageGenerator for OpenAiImageGenerator {
    fn model_identity(&self) -> (&str, &str) {
        ("openai-images", &self.model)
    }
    fn generate(
        &self,
        prompt: &str,
        recorder: &dyn crate::usage::AttemptRecorder,
    ) -> Result<GeneratedImage, ImageGenerationError> {
        let prompt = prompt.trim();
        if prompt.is_empty() {
            return Err(ImageGenerationError::InvalidPrompt);
        }
        if prompt.len() > MAX_IMAGE_PROMPT_BYTES {
            return Err(ImageGenerationError::PromptTooLarge);
        }

        let request = ImageRequest {
            model: &self.model,
            prompt,
            n: 1,
            size: "1024x1024",
            output_format: "png",
        };
        let attempt = recorder.begin(crate::usage::AttemptKind::Http)?;
        let response = self
            .agent
            .post(&self.endpoint)
            .header(
                "authorization",
                &format!("Bearer {}", self.api_key.expose()),
            )
            .header("accept", "application/json")
            .send_json(&request)
            .map_err(|source| ImageGenerationError::Request(source.to_string()))?;
        let status = response.status().as_u16();
        if !(200..300).contains(&status) {
            crate::model::read_error_body_recorded(response, recorder, attempt, false).map_err(
                |e| match e {
                    crate::model::ModelError::Accounting(e) => ImageGenerationError::Accounting(e),
                    _other => {
                        tracing::debug!(cause_type = "image-error-body");
                        ImageGenerationError::Response
                    }
                },
            )?;
            return Err(ImageGenerationError::Status(status));
        }
        let response = crate::usage::read_usage_json(
            response.into_parts().1.into_reader(),
            MAX_IMAGE_RESPONSE_BYTES,
            recorder,
            attempt,
            false,
        )
        .map_err(|error| match error {
            crate::model::ModelError::Accounting(error) => ImageGenerationError::Accounting(error),
            crate::model::ModelError::Response(ref detail)
                if detail == "response exceeded byte bound" =>
            {
                ImageGenerationError::TooLarge
            }
            _other => {
                tracing::debug!(cause_type = "image-response");
                ImageGenerationError::Response
            }
        })?;
        if !(200..300).contains(&status) {
            return Err(ImageGenerationError::Status(status));
        }
        let response: ImageResponse = serde_json::from_value(response).map_err(|error| {
            tracing::debug!(cause_type = "image-response", category = ?error.classify());
            ImageGenerationError::Response
        })?;
        if response.data.len() != 1 {
            return Err(ImageGenerationError::Response);
        }
        let encoded = response
            .data
            .into_iter()
            .next()
            .and_then(|image| image.b64_json)
            .filter(|value| !value.is_empty())
            .ok_or(ImageGenerationError::Response)?;
        let maximum_encoded = MAX_GENERATED_IMAGE_BYTES.div_ceil(3) * 4;
        if encoded.len() > maximum_encoded {
            return Err(ImageGenerationError::TooLarge);
        }
        #[allow(
            clippy::map_err_ignore,
            reason = "base64 DecodeError adds only an offset and the offending byte inside the \
                      service's inline image blob; InvalidEncoding already names both the field \
                      and the failure, and generated bytes are untrusted content this module \
                      never puts in a diagnostic"
        )]
        let data = STANDARD
            .decode(encoded)
            .map_err(|_| ImageGenerationError::InvalidEncoding)?;
        GeneratedImage::from_png(data)
    }
}

#[derive(Serialize)]
struct ImageRequest<'a> {
    model: &'a str,
    prompt: &'a str,
    n: u8,
    size: &'static str,
    output_format: &'static str,
}

#[derive(Deserialize)]
struct ImageResponse {
    #[serde(default)]
    data: Vec<ImageData>,
}

#[derive(Deserialize)]
struct ImageData {
    #[serde(default)]
    b64_json: Option<String>,
}

/// Stable image-generation failure.
#[derive(Clone, Debug, Eq, Error, PartialEq)]
pub enum ImageGenerationError {
    /// Ledger refusal; no subsequent transmission is permitted.
    #[error(transparent)]
    Accounting(#[from] crate::usage::AccountingError),
    /// Client configuration was invalid.
    #[error("invalid image generation configuration: {0}")]
    Configuration(String),
    /// The model-authored prompt was empty.
    #[error("image generation prompt must not be empty")]
    InvalidPrompt,
    /// The model-authored prompt exceeded the fixed input bound.
    #[error("image generation prompt exceeded the input bound")]
    PromptTooLarge,
    /// The HTTP request could not complete.
    ///
    /// Carries the transport diagnosis, which is the whole of what distinguishes a refused
    /// connection from a TLS failure or a timeout. [`Self::category`] stays fixed, so this does not
    /// widen telemetry cardinality.
    #[error("image generation request failed: {0}")]
    Request(String),
    /// The service refused the request.
    #[error("image generation service returned HTTP {0}")]
    Status(u16),
    /// The service response did not contain exactly one inline image.
    #[error("invalid image generation response")]
    Response,
    /// The encoded or decoded image exceeded the fixed byte ceiling.
    #[error("generated image exceeded the byte bound")]
    TooLarge,
    /// Inline image data was not valid base64.
    #[error("generated image had invalid base64 encoding")]
    InvalidEncoding,
    /// Decoded bytes were not a PNG.
    #[error("generated image was not a PNG")]
    InvalidImage,
}

impl ImageGenerationError {
    /// Stable low-cardinality category for payload-free telemetry.
    #[must_use]
    pub const fn category(&self) -> &'static str {
        match self {
            Self::Accounting(_) => "accounting",
            Self::Configuration(_) => "configuration",
            Self::InvalidPrompt => "invalid-prompt",
            Self::PromptTooLarge => "prompt-too-large",
            Self::Request(_) => "request",
            Self::Status(_) => "status",
            Self::Response => "response",
            Self::TooLarge => "too-large",
            Self::InvalidEncoding => "invalid-encoding",
            Self::InvalidImage => "invalid-image",
        }
    }
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use base64::{Engine as _, engine::general_purpose::STANDARD};
    use serde_json::{Value, json};

    use crate::mock::{MockResponse, MockServer};

    use super::{
        GeneratedImage, ImageGenerationError, ImageGenerator as _, MAX_GENERATED_IMAGE_BYTES,
        OpenAiImageGenerator, PNG_SIGNATURE,
    };

    fn png() -> Vec<u8> {
        let mut bytes = PNG_SIGNATURE.to_vec();
        bytes.extend_from_slice(b"bounded generated bytes");
        bytes
    }

    #[test]
    fn generated_image_debug_never_contains_bytes() {
        let image = GeneratedImage::from_png(png()).expect("valid PNG fixture");
        let debugged = format!("{image:?}");
        assert!(debugged.contains("image/png"));
        assert!(debugged.contains("31"));
        assert!(!debugged.contains("bounded generated bytes"));
    }

    #[test]
    fn public_images_request_returns_one_bounded_png() {
        let response = json!({
            "data": [{"b64_json": STANDARD.encode(png())}],
            "usage": {"total_tokens": 100}
        });
        let mock = MockServer::start(vec![MockResponse::json(response)]);
        let generator = OpenAiImageGenerator::with_endpoint(
            format!("{}/images/generations", mock.base_url()),
            "gpt-image-1",
            "image-secret".to_owned(),
            Duration::from_secs(1),
        )
        .expect("loopback client");

        let image = generator
            .generate(
                "draw a small orange cat",
                &crate::usage::AttemptLog::default(),
            )
            .expect("one generated image");
        assert_eq!(image.bytes(), png());

        let request = mock.requests().remove(0);
        let request_lower = request.to_ascii_lowercase();
        assert!(request_lower.contains("authorization: bearer image-secret"));
        let body = request.split("\r\n\r\n").nth(1).expect("request body");
        let body: Value = serde_json::from_str(body).expect("JSON request");
        assert_eq!(body["model"], "gpt-image-1");
        assert_eq!(body["prompt"], "draw a small orange cat");
        assert_eq!(body["n"], 1);
        assert_eq!(body["size"], "1024x1024");
        assert_eq!(body["output_format"], "png");
    }

    #[test]
    fn prompt_bounds_fail_before_any_network_request() {
        let generator = OpenAiImageGenerator::with_endpoint(
            "http://127.0.0.1:9",
            "gpt-image-1",
            "secret".to_owned(),
            Duration::from_secs(1),
        )
        .expect("client");
        assert_eq!(
            generator
                .generate("  ", &crate::usage::AttemptLog::default())
                .expect_err("empty prompt"),
            ImageGenerationError::InvalidPrompt
        );
        assert_eq!(
            generator
                .generate(
                    &"x".repeat(super::MAX_IMAGE_PROMPT_BYTES + 1),
                    &crate::usage::AttemptLog::default()
                )
                .expect_err("oversized prompt"),
            ImageGenerationError::PromptTooLarge
        );
    }

    /// "image generation request failed" on its own cannot be acted on: a refused connection, an
    /// unresolvable host, and a TLS rejection are three different operator problems that used to
    /// render as one string. The category stays fixed so telemetry cardinality does not move.
    #[test]
    fn a_failed_request_carries_the_transport_diagnosis() {
        let generator = OpenAiImageGenerator::with_endpoint(
            "http://127.0.0.1:9",
            "gpt-image-1",
            "secret".to_owned(),
            Duration::from_secs(1),
        )
        .expect("client");
        let error = generator
            .generate("cat", &crate::usage::AttemptLog::default())
            .expect_err("nothing listens on port 9");
        let ImageGenerationError::Request(ref detail) = error else {
            panic!("{error:?}");
        };
        assert!(!detail.is_empty(), "the transport cause survives the map");
        assert_eq!(error.category(), "request");
    }

    #[test]
    fn rejects_invalid_base64_png_count_status_and_oversized_images() {
        let invalid = MockServer::start(vec![MockResponse::json(
            json!({"data": [{"b64_json": "%%%"}]}),
        )]);
        let generator = OpenAiImageGenerator::with_endpoint(
            invalid.base_url(),
            "gpt-image-1",
            "secret".to_owned(),
            Duration::from_secs(1),
        )
        .expect("client");
        assert_eq!(
            generator
                .generate("cat", &crate::usage::AttemptLog::default())
                .expect_err("invalid base64"),
            ImageGenerationError::InvalidEncoding
        );

        let invalid_png = MockServer::start(vec![MockResponse::json(json!({
            "data": [{"b64_json": STANDARD.encode(b"not a png")}]
        }))]);
        let generator = OpenAiImageGenerator::with_endpoint(
            invalid_png.base_url(),
            "gpt-image-1",
            "secret".to_owned(),
            Duration::from_secs(1),
        )
        .expect("client");
        assert_eq!(
            generator
                .generate("cat", &crate::usage::AttemptLog::default())
                .expect_err("invalid PNG"),
            ImageGenerationError::InvalidImage
        );

        let multiple = MockServer::start(vec![MockResponse::json(json!({
            "data": [
                {"b64_json": STANDARD.encode(png())},
                {"b64_json": STANDARD.encode(png())}
            ]
        }))]);
        let generator = OpenAiImageGenerator::with_endpoint(
            multiple.base_url(),
            "gpt-image-1",
            "secret".to_owned(),
            Duration::from_secs(1),
        )
        .expect("client");
        assert_eq!(
            generator
                .generate("cats", &crate::usage::AttemptLog::default())
                .expect_err("multiple images"),
            ImageGenerationError::Response
        );

        let refused = MockServer::start(vec![MockResponse::failure(
            429,
            json!({"error": "secret detail"}),
        )]);
        let generator = OpenAiImageGenerator::with_endpoint(
            refused.base_url(),
            "gpt-image-1",
            "secret".to_owned(),
            Duration::from_secs(1),
        )
        .expect("client");
        assert_eq!(
            generator
                .generate("cat", &crate::usage::AttemptLog::default())
                .expect_err("HTTP refusal"),
            ImageGenerationError::Status(429)
        );

        let encoded = "A".repeat(MAX_GENERATED_IMAGE_BYTES.div_ceil(3) * 4 + 1);
        let oversized = MockServer::start(vec![MockResponse::json(
            json!({"data": [{"b64_json": encoded}]}),
        )]);
        let generator = OpenAiImageGenerator::with_endpoint(
            oversized.base_url(),
            "gpt-image-1",
            "secret".to_owned(),
            Duration::from_secs(2),
        )
        .expect("client");
        assert_eq!(
            generator
                .generate("cat", &crate::usage::AttemptLog::default())
                .expect_err("oversized image"),
            ImageGenerationError::TooLarge
        );
    }
}

#[cfg(test)]
mod accounting_tests {
    use super::*;
    use crate::{
        mock::{MockResponse, MockServer},
        usage::AttemptLog,
    };
    #[test]
    fn malformed_image_bytes_do_not_erase_reported_usage() {
        let mock = MockServer::start(vec![MockResponse::json(
            serde_json::json!({"data":[{"b64_json":"not base64"}],"usage":{"input_tokens":10,"output_tokens":20,"total_tokens":30}}),
        )]);
        let generator = OpenAiImageGenerator::with_endpoint(
            mock.base_url(),
            "fixture",
            "fixture-not-secret".into(),
            Duration::from_secs(2),
        )
        .unwrap();
        let log = AttemptLog::default();
        assert_eq!(
            generator.generate("draw a fruit", &log).unwrap_err(),
            ImageGenerationError::InvalidEncoding
        );
        assert_eq!(log.observations().len(), 1);
        assert_eq!(
            log.observations()[0].1.unwrap().usage.total_tokens,
            Some(30)
        );
    }
}
