-- Harden nullable rowid-table primary keys without rewriting retained evidence.
PRAGMA user_version = 2;
CREATE TRIGGER pk_artifact_insert BEFORE INSERT ON artifact WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_artifact_update BEFORE UPDATE ON artifact WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_assignment_insert BEFORE INSERT ON assignment WHEN NEW.experiment_id IS NULL OR NEW.factor_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_assignment_update BEFORE UPDATE ON assignment WHEN NEW.experiment_id IS NULL OR NEW.factor_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_attempt_insert BEFORE INSERT ON attempt WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_attempt_update BEFORE UPDATE ON attempt WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_build_insert BEFORE INSERT ON build WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_build_update BEFORE UPDATE ON build WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_campaign_insert BEFORE INSERT ON campaign WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_campaign_update BEFORE UPDATE ON campaign WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_comparison_group_insert BEFORE INSERT ON comparison_group WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_comparison_group_update BEFORE UPDATE ON comparison_group WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_comparison_member_insert BEFORE INSERT ON comparison_member WHEN NEW.group_id IS NULL OR NEW.experiment_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_comparison_member_update BEFORE UPDATE ON comparison_member WHEN NEW.group_id IS NULL OR NEW.experiment_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_environment_insert BEFORE INSERT ON environment WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_environment_update BEFORE UPDATE ON environment WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_experiment_insert BEFORE INSERT ON experiment WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_experiment_update BEFORE UPDATE ON experiment WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_experiment_dependency_insert BEFORE INSERT ON experiment_dependency WHEN NEW.experiment_id IS NULL OR NEW.predecessor_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_experiment_dependency_update BEFORE UPDATE ON experiment_dependency WHEN NEW.experiment_id IS NULL OR NEW.predecessor_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_experiment_prerequisite_insert BEFORE INSERT ON experiment_prerequisite WHEN NEW.experiment_id IS NULL OR NEW.prerequisite_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_experiment_prerequisite_update BEFORE UPDATE ON experiment_prerequisite WHEN NEW.experiment_id IS NULL OR NEW.prerequisite_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_factor_insert BEFORE INSERT ON factor WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_factor_update BEFORE UPDATE ON factor WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_factor_level_insert BEFORE INSERT ON factor_level WHEN NEW.factor_id IS NULL OR NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_factor_level_update BEFORE UPDATE ON factor_level WHEN NEW.factor_id IS NULL OR NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_finding_insert BEFORE INSERT ON finding WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_finding_update BEFORE UPDATE ON finding WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_followup_insert BEFORE INSERT ON followup WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_followup_update BEFORE UPDATE ON followup WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_followup_dependency_insert BEFORE INSERT ON followup_dependency WHEN NEW.followup_id IS NULL OR NEW.experiment_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_followup_dependency_update BEFORE UPDATE ON followup_dependency WHEN NEW.followup_id IS NULL OR NEW.experiment_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_hypothesis_insert BEFORE INSERT ON hypothesis WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_hypothesis_update BEFORE UPDATE ON hypothesis WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_hypothesis_reference_insert BEFORE INSERT ON hypothesis_reference WHEN NEW.hypothesis_id IS NULL OR NEW.reference_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_hypothesis_reference_update BEFORE UPDATE ON hypothesis_reference WHEN NEW.hypothesis_id IS NULL OR NEW.reference_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_metric_insert BEFORE INSERT ON metric WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_metric_update BEFORE UPDATE ON metric WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_missing_metric_insert BEFORE INSERT ON missing_metric WHEN NEW.attempt_id IS NULL OR NEW.metric_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_missing_metric_update BEFORE UPDATE ON missing_metric WHEN NEW.attempt_id IS NULL OR NEW.metric_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_parse_run_insert BEFORE INSERT ON parse_run WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_parse_run_update BEFORE UPDATE ON parse_run WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_phase_summary_insert BEFORE INSERT ON phase_summary WHEN NEW.parse_id IS NULL OR NEW.phase IS NULL OR NEW.metric_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_phase_summary_update BEFORE UPDATE ON phase_summary WHEN NEW.parse_id IS NULL OR NEW.phase IS NULL OR NEW.metric_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_prerequisite_insert BEFORE INSERT ON prerequisite WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_prerequisite_update BEFORE UPDATE ON prerequisite WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_prerequisite_evidence_insert BEFORE INSERT ON prerequisite_evidence WHEN NEW.prerequisite_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_prerequisite_evidence_update BEFORE UPDATE ON prerequisite_evidence WHEN NEW.prerequisite_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_proposed_control_insert BEFORE INSERT ON proposed_control WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_proposed_control_update BEFORE UPDATE ON proposed_control WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_provider_insert BEFORE INSERT ON provider WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_provider_update BEFORE UPDATE ON provider WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_provider_member_insert BEFORE INSERT ON provider_member WHEN NEW.set_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_provider_member_update BEFORE UPDATE ON provider_member WHEN NEW.set_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_provider_set_insert BEFORE INSERT ON provider_set WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_provider_set_update BEFORE UPDATE ON provider_set WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_recipe_insert BEFORE INSERT ON recipe WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_recipe_update BEFORE UPDATE ON recipe WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_reference_insert BEFORE INSERT ON reference WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_reference_update BEFORE UPDATE ON reference WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_resource_insert BEFORE INSERT ON resource WHEN NEW.attempt_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_resource_update BEFORE UPDATE ON resource WHEN NEW.attempt_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_sample_insert BEFORE INSERT ON sample WHEN NEW.parse_id IS NULL OR NEW.metric_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_sample_update BEFORE UPDATE ON sample WHEN NEW.parse_id IS NULL OR NEW.metric_id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_source_revision_insert BEFORE INSERT ON source_revision WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_source_revision_update BEFORE UPDATE ON source_revision WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_study_insert BEFORE INSERT ON study WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_study_update BEFORE UPDATE ON study WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_subsystem_insert BEFORE INSERT ON subsystem WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_subsystem_update BEFORE UPDATE ON subsystem WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_trial_insert BEFORE INSERT ON trial WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER pk_trial_update BEFORE UPDATE ON trial WHEN NEW.id IS NULL BEGIN SELECT RAISE(ABORT,'null relational identity'); END;
CREATE TRIGGER typed_level_update BEFORE UPDATE ON factor_level WHEN NEW.kind != (SELECT kind FROM factor WHERE id=NEW.factor_id) BEGIN SELECT RAISE(ABORT,'factor kind mismatch'); END;
CREATE TRIGGER fixed_attempt_condition BEFORE UPDATE ON attempt WHEN NEW.trial_id!=OLD.trial_id OR NEW.number!=OLD.number OR NEW.driver_sha256!=OLD.driver_sha256 OR NEW.condition_sha256!=OLD.condition_sha256 OR NEW.command_json!=OLD.command_json BEGIN SELECT RAISE(ABORT,'immutable attempt condition'); END;
CREATE TRIGGER fixed_resource_owner BEFORE UPDATE ON resource WHEN NEW.token!=OLD.token OR NEW.daemon_id!=OLD.daemon_id OR NEW.container_name!=OLD.container_name OR NEW.volume_name!=OLD.volume_name OR (OLD.container_id IS NOT NULL AND NEW.container_id IS NOT OLD.container_id) OR (OLD.created_at IS NOT NULL AND NEW.created_at IS NOT OLD.created_at) OR (OLD.started_at IS NOT NULL AND NEW.started_at IS NOT OLD.started_at) BEGIN SELECT RAISE(ABORT,'immutable process-tree identity'); END;
