package dekopon:broker-provider@0.3.0;

world provider {
    include dekopon:provider/provider@0.3.0;
    import dekopon:asset/asset@0.1.0;
    import dekopon:http/client@1.1.0;
    import dekopon:storage/jsonl@0.1.0;
    import dekopon:storage/durable-files@0.1.0;
    import dekopon:clock/wall@1.0.0;
    import dekopon:clock/wall@1.1.0;
    import dekopon:clock/monotonic@1.1.0;
    import dekopon:random/source@0.1.0;
    import dekopon:settings/config@0.1.0;
}
